#!/bin/bash

# Android device container is considered healthy if adb, stf provider/cli and appium up&running
# 0 - healthy
# 1 - unhealthy

kill_container() {
  echo $1
  # while $HOME/.healthy exists container is good.
  rm -f $HOME/.healthy
}

ADB_STATUS=$(adb devices | grep -c ${DEVICEUDID})
if [ ! "$ADB_STATUS" -eq "1" ]; then
  kill_container "adb server is dead. restarting container..."
  exit 0
fi

STFDEVICE_STATUS=$(ps -ef | grep -v "grep" | grep -c "cli device")
if [ ! "$STFDEVICE_STATUS" -eq "1" ]; then
  kill_container "stf device is dead. reastarting container..."
  exit 0
fi

STFPROVIDER_STATUS=$(ps -ef | grep -v "grep" | grep -c "stf provider")
if [ ! "$STFPROVIDER_STATUS" -eq "1" ]; then
  kill_container "stf provider is dead. reastarting container..."
  exit 0
fi

curl --silent http://localhost:$PORT/wd/hub/status | grep "\"status\":0"
if [[ ! $? -eq 0 ]]; then
  kill_container "appium provider is dead. reastarting container..."
  exit 0
fi
